# Generated by Django 6.0.2 on 2026-02-16 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название этапа')),
                ('round_number', models.PositiveIntegerField(verbose_name='Раунд')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн предиктов')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_covers/', verbose_name='Обложка')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('locked', 'Закрыто'), ('scored', 'Очки посчитаны')], default='open', max_length=10, verbose_name='Статус')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_photos/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='league.event')),
            ],
        ),
    ]
