# Generated by Django 6.0.2 on 2026-02-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_result_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='race_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время гонки'),
        ),
    ]
