# Generated by Django 6.0.2 on 2026-02-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_event_race_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='event_covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(max_length=255, upload_to='event_photos/', verbose_name='Фото'),
        ),
    ]
