# Generated by Django 6.0.2 on 2026-02-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_prediction_crazy_prediction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveSmallIntegerField(default=2026, verbose_name='Сезон')),
                ('hungary_driver_championship_leader', models.CharField(choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], max_length=50, verbose_name='Лидер чемпионата пилотов после этапа Венгрии')),
                ('hungary_constructor_championship_leader', models.CharField(choices=[('mclaren', 'McLaren'), ('mercedes', 'Mercedes'), ('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('williams', 'Williams'), ('racing_bulls', 'Racing Bulls'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('audi', 'Audi'), ('alpine', 'Alpine'), ('cadillac', 'Cadillac')], max_length=50, verbose_name='Лидер Кубка конструкторов после этапа Венгрии')),
                ('hadjar_best_finish', models.PositiveSmallIntegerField(verbose_name='Самый высокий финиш Хаджара')),
                ('world_drivers_champion', models.CharField(choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], max_length=50, verbose_name='Чемпион мира среди пилотов')),
                ('constructors_champion', models.CharField(choices=[('mclaren', 'McLaren'), ('mercedes', 'Mercedes'), ('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('williams', 'Williams'), ('racing_bulls', 'Racing Bulls'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('audi', 'Audi'), ('alpine', 'Alpine'), ('cadillac', 'Cadillac')], max_length=50, verbose_name='Чемпион Кубка конструкторов')),
                ('constructors_second', models.CharField(choices=[('mclaren', 'McLaren'), ('mercedes', 'Mercedes'), ('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('williams', 'Williams'), ('racing_bulls', 'Racing Bulls'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('audi', 'Audi'), ('alpine', 'Alpine'), ('cadillac', 'Cadillac')], max_length=50, verbose_name='2 место Кубка конструкторов')),
                ('constructors_third', models.CharField(choices=[('mclaren', 'McLaren'), ('mercedes', 'Mercedes'), ('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('williams', 'Williams'), ('racing_bulls', 'Racing Bulls'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('audi', 'Audi'), ('alpine', 'Alpine'), ('cadillac', 'Cadillac')], max_length=50, verbose_name='3 место Кубка конструкторов')),
                ('last_race_winner', models.CharField(choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], max_length=50, verbose_name='Победитель последней гонки сезона')),
                ('season_pole_sitter', models.CharField(choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], max_length=50, verbose_name='Pole-sitter сезона')),
                ('driver_change_happened', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3, verbose_name='Была ли смена пилота в сезоне')),
                ('team_most_dnf', models.CharField(choices=[('mclaren', 'McLaren'), ('mercedes', 'Mercedes'), ('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('williams', 'Williams'), ('racing_bulls', 'Racing Bulls'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('audi', 'Audi'), ('alpine', 'Alpine'), ('cadillac', 'Cadillac')], max_length=50, verbose_name='Команда-лидер по количеству DNF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('season_year', 'user__username'),
                'unique_together': {('user', 'season_year')},
            },
        ),
    ]
