# Generated by Django 6.0.2 on 2026-02-28 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_seasonprediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveSmallIntegerField(default=2026, unique=True, verbose_name='Сезон')),
                ('hungary_driver_championship_leader', models.CharField(choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], max_length=50, verbose_name='Лидер чемпионата пилотов после этапа Венгрии (факт)')),
                ('hungary_constructor_championship_leader', models.CharField(choices=[('mclaren', 'McLaren'), ('mercedes', 'Mercedes'), ('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('williams', 'Williams'), ('racing_bulls', 'Racing Bulls'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('audi', 'Audi'), ('alpine', 'Alpine'), ('cadillac', 'Cadillac')], max_length=50, verbose_name='Лидер Кубка конструкторов после этапа Венгрии (факт)')),
                ('hadjar_best_finish', models.PositiveSmallIntegerField(verbose_name='Самый высокий финиш Хаджара (факт)')),
                ('world_drivers_champion', models.CharField(choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], max_length=50, verbose_name='Чемпион мира среди пилотов (факт)')),
                ('constructors_champion', models.CharField(choices=[('mclaren', 'McLaren'), ('mercedes', 'Mercedes'), ('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('williams', 'Williams'), ('racing_bulls', 'Racing Bulls'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('audi', 'Audi'), ('alpine', 'Alpine'), ('cadillac', 'Cadillac')], max_length=50, verbose_name='Чемпион Кубка конструкторов (факт)')),
                ('constructors_second', models.CharField(choices=[('mclaren', 'McLaren'), ('mercedes', 'Mercedes'), ('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('williams', 'Williams'), ('racing_bulls', 'Racing Bulls'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('audi', 'Audi'), ('alpine', 'Alpine'), ('cadillac', 'Cadillac')], max_length=50, verbose_name='2 место Кубка конструкторов (факт)')),
                ('constructors_third', models.CharField(choices=[('mclaren', 'McLaren'), ('mercedes', 'Mercedes'), ('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('williams', 'Williams'), ('racing_bulls', 'Racing Bulls'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('audi', 'Audi'), ('alpine', 'Alpine'), ('cadillac', 'Cadillac')], max_length=50, verbose_name='3 место Кубка конструкторов (факт)')),
                ('last_race_winner', models.CharField(choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], max_length=50, verbose_name='Победитель последней гонки сезона (факт)')),
                ('season_pole_sitter', models.CharField(choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], max_length=50, verbose_name='Pole-sitter сезона (факт)')),
                ('driver_change_happened', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3, verbose_name='Была ли смена пилота в сезоне (факт)')),
                ('team_most_dnf', models.CharField(choices=[('mclaren', 'McLaren'), ('mercedes', 'Mercedes'), ('red_bull', 'Red Bull'), ('ferrari', 'Ferrari'), ('williams', 'Williams'), ('racing_bulls', 'Racing Bulls'), ('aston_martin', 'Aston Martin'), ('haas', 'Haas'), ('audi', 'Audi'), ('alpine', 'Alpine'), ('cadillac', 'Cadillac')], max_length=50, verbose_name='Команда-лидер по количеству DNF (факт)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('season_year',),
            },
        ),
        migrations.CreateModel(
            name='SeasonScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveSmallIntegerField(default=2026, verbose_name='Сезон')),
                ('points', models.IntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('season_year', '-points', 'user__username'),
                'unique_together': {('user', 'season_year')},
            },
        ),
    ]
