# Generated by Django 6.0.2 on 2026-03-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок')),
                ('image', models.ImageField(max_length=255, upload_to='home_results/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=220, verbose_name='Подпись')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото результатов (главная)',
                'verbose_name_plural': 'Фото результатов (главная)',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
    ]
