# Generated by Django 6.0.2 on 2026-03-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_result_driver_of_day_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_world_predict_champion',
            field=models.BooleanField(default=False, verbose_name='World Predict Champion'),
        ),
    ]
