# Generated by Django 6.0.2 on 2026-03-08

from django.db import migrations


def create_missing_user_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("league", "UserProfile")

    existing_user_ids = set(UserProfile.objects.values_list("user_id", flat=True))
    missing_profiles = [
        UserProfile(user_id=user_id)
        for user_id in User.objects.values_list("id", flat=True)
        if user_id not in existing_user_ids
    ]
    if missing_profiles:
        UserProfile.objects.bulk_create(missing_profiles, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0012_userprofile_is_world_predict_champion"),
    ]

    operations = [
        migrations.RunPython(create_missing_user_profiles, migrations.RunPython.noop),
    ]
