# Generated by Django 6.0.2 on 2026-03-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_event_has_sprint_prediction_sprint_qualifying_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='has_sprint',
            field=models.BooleanField(default=False, verbose_name='Есть спринт'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='sprint_qualifying_winner',
            field=models.CharField(blank=True, choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], default='', max_length=50, verbose_name='Победитель квалификации к спринту'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='sprint_winner',
            field=models.CharField(blank=True, choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], default='', max_length=50, verbose_name='Победитель спринта'),
        ),
        migrations.AlterField(
            model_name='result',
            name='sprint_qualifying_winner',
            field=models.CharField(blank=True, choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], default='', max_length=50, verbose_name='Победитель квалификации к спринту (факт)'),
        ),
        migrations.AlterField(
            model_name='result',
            name='sprint_winner',
            field=models.CharField(blank=True, choices=[('norris', 'Норрис (McLaren)'), ('piastri', 'Пиастри (McLaren)'), ('russell', 'Рассел (Mercedes)'), ('antonelli', 'Антонелли (Mercedes)'), ('verstappen', 'Ферстаппен (Red Bull)'), ('hadjar', 'Хаджар (Red Bull)'), ('leclerc', 'Леклер (Ferrari)'), ('hamilton', 'Хэмильтон (Ferrari)'), ('albon', 'Албон (Williams)'), ('sainz', 'Сайнс (Williams)'), ('lindblad', 'Линдблад (Racing Bulls)'), ('lawson', 'Лоусон (Racing Bulls)'), ('stroll', 'Стролл (Aston Martin)'), ('alonso', 'Алонсо (Aston Martin)'), ('ocon', 'Окон (Haas)'), ('bearman', 'Берман (Haas)'), ('hulkenberg', 'Хюлкенберг (Audi)'), ('bortoleto', 'Бортолето (Audi)'), ('gasly', 'Гасли (Alpine)'), ('colapinto', 'Колапинто (Alpine)'), ('perez', 'Перес (Cadillac)'), ('bottas', 'Боттас (Cadillac)')], default='', max_length=50, verbose_name='Победитель спринта (факт)'),
        ),
    ]
