# Generated by Django 6.0.2 on 2026-07-30 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_telegram_link_tokens(apps, schema_editor):
    UserProfile = apps.get_model("league", "UserProfile")
    for profile in UserProfile.objects.all().iterator():
        profile.telegram_link_token = uuid.uuid4()
        profile.save(update_fields=("telegram_link_token",))


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0016_allow_partial_season_results"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramBotState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="default", editable=False, max_length=32, unique=True
                    ),
                ),
                ("update_offset", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telegram chat ID"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram_link_token",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Токен привязки Telegram",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Telegram-уведомления"
            ),
        ),
        migrations.CreateModel(
            name="TelegramReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_reminders",
                        to="league.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at",),
                "unique_together": {("event", "user")},
            },
        ),
        migrations.RunPython(seed_telegram_link_tokens, migrations.RunPython.noop),
    ]
