# Generated by Django 6.0.2 on 2026-07-31 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_season(apps, schema_editor):
    Season = apps.get_model("league", "Season")
    Season.objects.get_or_create(
        year=2026,
        defaults={"title": "F1 Predictions 2026", "is_active": True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0017_telegrambotstate_userprofile_telegram_chat_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("scores", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Версия подсчёта",
                "verbose_name_plural": "Версии подсчёта",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(unique=True, verbose_name="Год"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активный сезон"),
                ),
                (
                    "predictions_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дедлайн сезонных предиктов"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Сезон",
                "verbose_name_plural": "Сезоны",
                "ordering": ("-year",),
            },
        ),
        migrations.RunPython(create_initial_season, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["season_year", "round_number"]},
        ),
        migrations.AlterUniqueTogether(
            name="telegramreminder",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="event",
            name="season_year",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=2026, verbose_name="Сезон"
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="published_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="telegramreminder",
            name="kind",
            field=models.CharField(
                choices=[
                    ("24h", "За 24 часа"),
                    ("3h", "За 3 часа"),
                    ("result", "Результат этапа"),
                ],
                default="3h",
                max_length=10,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="telegramreminder",
            unique_together={("event", "user", "kind")},
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("season_year", "round_number"),
                name="unique_event_round_per_season",
            ),
        ),
        migrations.AddField(
            model_name="scorerevision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="score_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scorerevision",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="score_revisions",
                to="league.event",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorerevision",
            constraint=models.UniqueConstraint(
                fields=("event", "revision"), name="unique_score_revision_per_event"
            ),
        ),
    ]
