# Generated by Django 6.0.2 on 2026-07-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0018_scorerevision_season_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeresultimage",
            name="season_year",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=2026, verbose_name="Сезон"
            ),
        ),
    ]
