# Generated by Django 6.0.2 on 2026-08-04 13:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0021_global_duel_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WildcardSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="default", editable=False, max_length=32, unique=True
                    ),
                ),
                (
                    "card_back_image",
                    models.ImageField(
                        blank=True,
                        help_text="Необязательно. Одна картинка используется для всех этапов.",
                        max_length=255,
                        null=True,
                        upload_to="wildcard_theme/",
                        verbose_name="Общая рубашка личных карт",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Оформление личных карт",
                "verbose_name_plural": "Оформление личных карт",
            },
        ),
        migrations.CreateModel(
            name="EventWildcardQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=240, verbose_name="Вопрос")),
                (
                    "option_a",
                    models.CharField(max_length=120, verbose_name="Вариант A"),
                ),
                (
                    "option_b",
                    models.CharField(max_length=120, verbose_name="Вариант B"),
                ),
                (
                    "correct_option",
                    models.CharField(
                        blank=True,
                        choices=[("a", "Вариант A"), ("b", "Вариант B")],
                        default="",
                        help_text="Заполни после завершения этапа перед публикацией очков.",
                        max_length=1,
                        verbose_name="Правильный вариант",
                    ),
                ),
                (
                    "points",
                    models.PositiveSmallIntegerField(
                        default=5,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Очки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Участвует в розыгрыше"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wildcard_questions",
                        to="league.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Личная карта этапа",
                "verbose_name_plural": "Личные карты этапов",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="PlayerWildcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_slot",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Выбранная карта",
                    ),
                ),
                (
                    "selected_option",
                    models.CharField(
                        blank=True,
                        choices=[("a", "Вариант A"), ("b", "Вариант B")],
                        default="",
                        max_length=1,
                        verbose_name="Ответ игрока",
                    ),
                ),
                ("drawn_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ответ сохранён"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_wildcards",
                        to="league.event",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="draws",
                        to="league.eventwildcardquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_wildcards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Выданная личная карта",
                "verbose_name_plural": "Выданные личные карты",
                "ordering": ("event", "user__username"),
            },
        ),
        migrations.AddIndex(
            model_name="eventwildcardquestion",
            index=models.Index(
                fields=["event", "is_active"], name="wildcard_event_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerwildcard",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_wildcard_draw_per_event_user"
            ),
        ),
    ]
