# Generated by Django 6.0.2 on 2026-09-27 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0026_arcade_records"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="qualifying_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время окончания квалификации"
            ),
        ),
        migrations.CreateModel(
            name="ArcadeWheelSpin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winner_score",
                    models.PositiveIntegerField(verbose_name="Результат победителя"),
                ),
                (
                    "prize",
                    models.CharField(
                        choices=[
                            ("pit_wall", "Бонус пит-уолла +2"),
                            ("card_boost", "ДРС личной карты +3"),
                            ("podium_edit", "Апдейт подиума"),
                            ("va_bank", "Ва-банк"),
                            ("ruel_v_govne", "Руль в говне"),
                            ("crazy_block", "Блок Crazy"),
                        ],
                        max_length=24,
                        verbose_name="Приз",
                    ),
                ),
                (
                    "activation_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Параметры активации"
                    ),
                ),
                (
                    "spun_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время прокрутки"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время активации"
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arcade_wheel_spin",
                        to="league.event",
                        verbose_name="Этап",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arcade_wheel_targets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Цель эффекта",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arcade_wheel_spins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Победитель аркады",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прокрут колеса аркады",
                "verbose_name_plural": "Прокруты колеса аркады",
            },
        ),
    ]
