# Generated by Django 6.0.2 on 2026-10-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0029_crazy_prediction_vote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArcadeLeadChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "best_score",
                    models.PositiveIntegerField(verbose_name="Рекорд на момент лидерства"),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(verbose_name="Попытки к моменту лидерства"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время смены лидера"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arcade_lead_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смена лидера аркады",
                "verbose_name_plural": "Смены лидера аркады",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
