# Generated by Django 6.0.2 on 2026-10-01 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_incorrect_all_time_trophies(apps, schema_editor):
    ArcadeTrophyAward = apps.get_model("league", "ArcadeTrophyAward")
    ArcadeTrophyAward.objects.using(schema_editor.connection.alias).filter(
        source_lead_change__isnull=False
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0031_arcade_trophy_award"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_incorrect_all_time_trophies, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="arcadetrophyaward",
            name="source_lead_change",
        ),
        migrations.AddField(
            model_name="arcadetrophyaward",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arcade_trophy_awards",
                to="league.event",
                verbose_name="Этап",
            ),
        ),
        migrations.AddField(
            model_name="arcadetrophyaward",
            name="game_key",
            field=models.CharField(
                default="pit_lane_flight",
                help_text="Стабильный идентификатор игры; для одной игры можно выдать один трофей за этап.",
                max_length=80,
                verbose_name="Код игры",
            ),
        ),
        migrations.AddConstraint(
            model_name="arcadetrophyaward",
            constraint=models.UniqueConstraint(
                fields=("event", "game_key"), name="uniq_arcade_trophy_event_game"
            ),
        ),
    ]
