# Generated by Django 6.0.2 on 2026-10-01 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0032_remove_arcadetrophyaward_source_lead_change_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArcadeGameClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_key",
                    models.CharField(
                        default="pit_lane_flight",
                        max_length=80,
                        verbose_name="Код игры",
                    ),
                ),
                (
                    "season_year",
                    models.PositiveSmallIntegerField(
                        default=2026, verbose_name="Сезон"
                    ),
                ),
                (
                    "winner_score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Результат победителя"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Попытки победителя"
                    ),
                ),
                ("closed_at", models.DateTimeField(verbose_name="Дедлайн закрытия")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arcade_game_closures",
                        to="league.event",
                        verbose_name="Этап закрытия",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arcade_game_closures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Зафиксированный победитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Закрытие мини-игры",
                "verbose_name_plural": "Закрытия мини-игр",
                "ordering": ("-closed_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game_key", "season_year"),
                        name="uniq_arcade_game_closure_season",
                    )
                ],
            },
        ),
    ]
