# Generated by Django 6.0.2 on 2026-10-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0033_arcadegameclosure"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="crazy_vote_closed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Время досрочного закрытия Paddock Jury",
            ),
        ),
    ]
